### ISSUE TITLE
kind構築の自動化

### ISSUE THREAD

**Issue by HamaguchiKazuki** [fun-dev/backend_dev#1]
# 概要
[環境構築](https://cloud-fun.esa.io/posts/145)に従って，wsl2上にkind(kubernetes in docker)を構築したい．

# タスクリスト
- [x] : wsl2の環境を構築
- [ ] : dind(docker in docker)の動作確認
- [ ] : kindの動作確認
- [ ] : Dockerfileに記述して自動化する

## 課題
dindが動作しない
```
docker: error during connect: Post http://docker:2375/v1.39/containers/create: dial tcp: lookup docker on 192.168.133.1:53: no such host.
See 'docker run --help'.
```

**Comment by materialofmouse** [comment]
使わなくなった。
